language: go
go:
  - 1.9
sudo: required
services:
  - docker
jobs:
  include:
    - stage: go_test
      script:
        - go test -v
    - stage: go_vet
      script:
        - go vet -v
    - stage: linux_docker_x86
      script:
        - docker pull golang:1.9.2
        - docker pull alpine:3.7
        - make docker
